version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main
          post-steps:
            - run: heroku run rails db:migrate --app do-goodr-be
jobs:
  build:
    parallelism: 1
    docker:
      services:
        - redis:latest
      - image: circleci/ruby:2.7.2
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: do-goodr-be_test
    environment:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      PGHOST: 127.0.0.1
      PGUSER: postgres
      RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - fast-inlet-74665-bundle-v2-{{ checksum "Gemfile.lock" }}
            - fast-inlet-74665-bundle-v2-
      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle install
      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: fast-inlet-74665-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: sudo apt install -y postgresql-client || true
      - run:
          name: Setup DB
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: Run Test Suite
          command: bundle exec rspec -fd
